DigitalLibrary/DigitalLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('our_auth/', include('our_auth.urls')),
    path('materials/', include('materials.urls')),
    path('users/', include('users.urls')),
    path('copyright/', include('copyright.urls')),
]

DigitalLibrary/copyright/urls.py
from django.urls import path
from . import views

app_name = 'copyright'
urlpatterns = [
    path('claim/', views.claim, name='claim'),
    path('claims_list/', views.claims_list, name='claims_list'),
    path('claim_success/', views.claim_success, name='claim_success'),
    path('remove_claim/<int:claim_id>', views.remove_claim, name='remove_claim'),
]

DigitalLibrary/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('user_info/<int:user_id>', views.user_info, name='user_info'),
]

DigitalLibrary/copyright/models.py
from django.contrib.auth.models import User
from django.db import models


class CopyrightClaim(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=127)
    body = models.TextField()
    telegram_alias = models.CharField(max_length=127)

DigitalLibrary/copyright/forms.py
from django import forms

from copyright.models import CopyrightClaim


class CopyrightClaimForm(forms.ModelForm):
    title = forms.CharField(max_length=127, label='Title')
    body = forms.Textarea()
    telegram_alias = forms.CharField(max_length=127, label='Telegram Alias')

    class Meta:
        model = CopyrightClaim
        fields = ('title', 'body', 'telegram_alias')

DigitalLibrary/copyright/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from copyright.forms import CopyrightClaimForm
from copyright.models import CopyrightClaim


def claim(request):
    if request.method == 'POST':
        form = CopyrightClaimForm(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.user_id = request.user.id
            model.save()
            return redirect('/copyright/claim_success')
        else:
            messages.error(request, form.errors)
    else:
        return render(request, 'copyright/claim.html', {'form': CopyrightClaimForm()})


def claims_list(request):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    list = CopyrightClaim.objects.all()
    return render(request, 'copyright/claims_list.html', {'list': list})


def claim_success(request):
    return render(request, 'copyright/claim_success.html')


def remove_claim(request, claim_id):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    try:
        claim = CopyrightClaim.objects.get(pk=claim_id)
        claim.delete()
        return redirect('/copyright/claims_list')
    except CopyrightClaim.DoesNotExist:
        return render(request, '400.html', {'message': 'Invalid claim_id passed'})

DigitalLibrary/copyright/templates/copyright/claim.html
{% extends "base.html" %}

{% block content %}
    <h1>Make a copyright complaint</h1>
    <hr>
    <form method="post" action="{% url 'copyright:claim' %}">
        {% csrf_token %}

        {{ form.as_table }}
        <input style="margin-left: auto; margin-right: auto;" type="submit" value="Send">
    </form>
{% endblock %}

DigitalLibrary/copyright/templates/copyright/claim_success.html
{% extends "base.html" %}

{% block content %}
    <h1>Copyright claim</h1>
    <p>Your claim was successfully submitted.</p>
    <p>Wait for the moderator to contact you via Telegram.</p>
{% endblock %}

DigitalLibrary/copyright/templates/copyright/claims_list.html
{% extends "base.html" %}

{% block content %}
    <style>
        h1, h2, h3, h4, h5, h6 {
            text-align: center;
        }

        td, th {
            padding: 6px 16px;
            text-align: left;
        }

        th {
            white-space: nowrap;
        }

        .claim {
            background-color: var(--background-alt);
            border-radius: 8px;
            padding: 8px;
            margin: 8px 0;
        }
    </style>

    <h1>Copyright claims</h1>
    <hr>

    {% if list %}
        {% for e in list %}
            <div class="claim">
                <table>
                    <tr style="border-bottom: 1px solid var(--background-alt2);">
                        <th>Claimer</th>
                        <td><a href="/users/user_info/{{ e.user_id }}">{{ e.user.username }}</a></td>
                    </tr>
                    <tr style="border-bottom: 1px solid var(--background-alt2);">
                        <th>Title</th>
                        <td>{{ e.title }}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid var(--background-alt2);">
                        <th>Body</th>
                        <td style="text-align: justify">{{ e.body|linebreaks }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <a class="fake-link" href="/copyright/remove_claim/{{ e.id }}">
                                <button class="dangerous-button">Remove</button>
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
        {% endfor %}

    {% else %}
        <p style="margin-left: auto; margin-right: auto;">No claims were made. Come back later!</p>
    {% endif %}


{% endblock %}