DigitalLibrary/DigitalLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('our_auth/', include('our_auth.urls')),
    path('materials/', include('materials.urls')),
    path('users/', include('users.urls')),
    path('copyright/', include('copyright.urls')),
]

DigitalLibrary/materials/urls.py
from django.urls import path
from . import views

app_name = 'materials'
urlpatterns = [
    path('course_page/<str:course_uuid>', views.course_page, name='course_page'),
    path('course_list/', views.course_list, name='course_list'),
    path('create_course/', views.create_course, name='create_course'),
    path('edit_section/<str:section_uuid>', views.edit_section, name='edit_section'),
    path('delete_section_from_course/<str:course_uuid>/<str:section_uuid>', views.delete_section_from_course, name='delete_section_from_course'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('file_info/<str:file_hash>', views.file_info, name='file_info'),
    path('file_list', views.file_list, name='file_list'),
    path('save_section/<str:section_uuid>', views.save_section, name='save_section'),
    path('save_course_name_subtitle/<str:course_uuid>', views.save_course_name_subtitle, name='save_course_name_subtitle'),
    path('validate_course_structure/<str:course_uuid>', views.validate_course_structure, name='validate_course_structure'),
    path('api_fetch_file_list', views.api_fetch_file_list, name='api_fetch_file_list'),
    path('download/<str:file_hash>', views.download, name='download'),
    path('material_request', views.material_request, name='material_request'),
    path('material_request_success', views.material_request_success, name='material_request_success'),
    path('material_requests_list', views.material_requests_list, name='material_requests_list'),
    path('remove_material_request/<int:req_id>', views.remove_material_request, name='remove_material_request'),
    path('delete_file/<str:file_hash>', views.delete_file, name='delete_file'),
    path('searchbar_search/<str:query>', views.searchbar_search, name='searchbar_search'),
    path('section_page/<str:section_uuid>', views.section_page, name='section_page'),
]

DigitalLibrary/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('user_info/<int:user_id>', views.user_info, name='user_info'),
]

DigitalLibrary/material_api/models/section.py
from pymodm import fields, MongoModel, EmbeddedMongoModel

from .content import ContentBase


class Section(MongoModel):
    uuid = fields.UUIDField(primary_key=True, required=True)
    name = fields.CharField(required=True)
    # List of tags represented as strings
    tags = fields.ListField(fields.CharField(), blank=True)
    contents = fields.EmbeddedDocumentListField(ContentBase, blank=True)

    def __str__(self):
        return 'Section(uuid=%s, name=%s, contents=%s)' % (self.uuid, self.name, self.contents)

DigitalLibrary/materials/models.py
from django.contrib.auth.models import User
from django.db import models


class MaterialRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=127)
    body = models.TextField()
    telegram_alias = models.CharField(max_length=127)

DigitalLibrary/materials/forms.py
from django import forms

from material_api.models.course import Course
from materials.models import MaterialRequest
from our_auth.models import SignupSubmission


class CreateCourseForm(forms.Form):
    name = forms.CharField(max_length=255, label='Course name')
    subtitle = forms.CharField(max_length=255, label='Course subtitle')


class UploadFileForm(forms.Form):
    name = forms.CharField(max_length=255)
    file = forms.FileField()


class MaterialRequestForm(forms.ModelForm):
    title = forms.CharField(max_length=127, label='Title')
    body = forms.Textarea()
    telegram_alias = forms.CharField(max_length=127, label='Telegram Alias')

    class Meta:
        model = MaterialRequest
        fields = ('title', 'body', 'telegram_alias')

DigitalLibrary/materials/views.py
import json
import uuid
from json import JSONDecodeError

from django.contrib import messages
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from pymodm.errors import DoesNotExist

from DigitalLibrary import utils, icons
from material_api import search
from material_api.models.content import ContentFile
from material_api.models.course import Course
from material_api.models.file import File
from material_api.models.section import Section
from materials.forms import CreateCourseForm, UploadFileForm, MaterialRequestForm
from materials.models import MaterialRequest
from users import user_api


def course_list(request):
    courses = list(Course.objects.all())

    # TODO: implement group checking
    # TODO: implement recent courses

    return render(request, 'course_list.html', {'courses': courses})


def validate_course_structure(request, course_uuid):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    try:
        course = Course.objects.get({'_id': uuid.UUID(course_uuid)})

        changed = False
        for section in course.sections:
            print(section)
            if section is None:
                course.sections.remove(section)
                changed = True

        if changed:
            course.save()

        return redirect('/materials/course_page/%s' % course_uuid)
    except Course.DoesNotExist:
        return render(request, '404.html', {'message': 'Course with given UUID was not found'})


def course_page(request, course_uuid):
    try:
        course = Course.objects.get({'_id': uuid.UUID(course_uuid)})

        icons_dict = {}
        for section in course.sections:
            for content in section.contents:
                if type(content) == ContentFile:
                    file = content.file
                    if file is not None:
                        icons_dict[file.hash] = icons.getIconURL(file.extension)

        return render(request, 'course_page.html',
                      {'course': course, 'icons': icons_dict, 'edit': request.GET.get('edit', 'false')})
    except ValueError:
        return render(request, '404.html', {'message': 'Your link is corrupted, please, recheck it'})
    except Course.DoesNotExist:
        return render(request, '404.html', {'message': 'Course with given UUID was not found'})


def create_course(request):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    if request.method == 'POST':
        form = CreateCourseForm(request.POST)
        if form.is_valid():
            data = request.POST.copy()
            color1, color2 = Course.gen_color()
            name = data.get('name')
            course = Course(uuid.uuid4(), name, data.get('subtitle'), color1, color2, [
                Section(uuid.uuid4(), 'Information about ' + name, [], []),
                Section(uuid.uuid4(), 'Books: ' + name, [], []),
                Section(uuid.uuid4(), 'Videos: ' + name, [], []),
                Section(uuid.uuid4(), 'Links: ' + name, [], [])
            ])
            course.save(cascade=True)
            return redirect('/materials/course_page/%s' % course.uuid)
        else:
            messages.error(request, form.errors)
    else:
        return render(request, 'create_course.html', {'form': CreateCourseForm()})


def edit_section(request, section_uuid):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    try:
        if section_uuid == 'new':
            # We are trying to create new section

            # Check if we know which course attach this section to
            course = request.GET.get('course_uuid', None)
            if course is None:
                return render(request, '400.html',
                              {'message': {'Trying to create a new section, but no course is specified for it.'}})

            new = True
            section = Section(uuid.uuid4(), 'New section', [], [])
        else:
            # We are updating existing section
            new = False
            section = Section.objects.get({'_id': uuid.UUID(section_uuid)})

        son = section.to_son()

        print(son)

        # Custom handling of content list, since we want to include their content into response, not just _id's.
        for i, c in enumerate(son['contents']):
            if c['type'] == 'file':
                # Check if non-existing file is referenced
                if section.contents[i].file is None:
                    c['file_info'] = File(hash='', name='ERROR! FILE DOES NOT EXIST').to_son()
                else:
                    c['file_info'] = section.contents[i].file.to_son()

        section_document = json.dumps(son.to_dict(), cls=DjangoJSONEncoder) \
            .replace('\\', '\\\\').replace('<', '\\<').replace('>', '\\>')

        return render(request, 'section_editor.html',
                      {'new': new, 'section': section, 'section_document': section_document})
    except ValueError:
        return render(request, '400.html', {'message': 'Your link is corrupted, please, recheck it'})
    except Course.DoesNotExist:
        return render(request, '404.html', {'message': 'Course with given UUID was not found'})
    except Section.DoesNotExist:
        return render(request, '404.html', {'message': 'Section with given UUID was not found'})


def delete_section_from_course(request, course_uuid, section_uuid):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    try:
        course = Course.objects.get({'_id': uuid.UUID(course_uuid)})
        section = Section.objects.get({'_id': uuid.UUID(section_uuid)})
        approved = request.GET.get('approved', 'false')

        # TODO: complete this!
        if approved == 'true':
            course.sections.remove(section)
            course.save()
            return redirect('/materials/course_page/' + course_uuid)
        else:
            return render(request, 'delete_section_from_course.html', {'course': course, 'section': section})
    except ValueError:
        return render(request, '400.html', {'message': 'Your link is corrupted, please, recheck it'})
    except Course.DoesNotExist:
        return render(request, '404.html', {'message': 'Course with given UUID was not found'})
    except Section.DoesNotExist:
        return render(request, '404.html', {'message': 'Section with given UUID was not found'})


def upload_file(request):
    """
    Serves the page for file upload and accepts files sent with file upload form.

    :param request: Django request object
    :return: page with form or redirection to page with info about newly uploaded file
    """
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            # Only allow direct upload for moderators, for all other users, set "pending" flag.
            pending = not request.user.has_perm('auth:moderate')
            f = File.create_from_data(request.user.id, pending, form.cleaned_data.get('name'), request.FILES['file'])
            return redirect('/materials/file_info/%s' % f.hash)
    else:
        form = UploadFileForm()
    return render(request, 'upload_file.html', {'form': form})


def file_info(request, file_hash):
    try:
        file = File.objects.get({'_id': file_hash})
    except File.DoesNotExist:
        return render(request, '404.html', {'message': 'File with given hash was not found'})

    uploader_name = ''
    if request.user.has_perm('auth.moderate'):
        uploader_name = user_api.get_username(file.uploader)

    icon = icons.getIconURL(file.extension)

    return render(request, 'file_info.html', {'file': file, 'uploader_name': uploader_name, 'icon': icon})


def file_list(request):
    # Get page number, if any was provided by user in the "page" argument
    page_number = request.GET.get('page', 0)
    if type(page_number) == str:
        try:
            page_number = int(page_number)
        except ValueError:
            return render(request, '400.html', {'message': 'Page number should be integer number'})

    page_size = 5

    files = File.objects.skip(page_number * page_size).limit(page_size).all()

    return render(request, 'file_list.html', {'page': page_number, 'files': files})


def save_section(request, section_uuid):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    # only accept POST requests here
    if request.method != 'POST':
        return render(request, '400.html', {'message': 'Expected POST request'})

    try:
        section = json.loads(request.body)

        # Check if we are creating new section & attaching it to the course
        course_uuid = request.GET.get('course_uuid', None)
        course = None
        if course_uuid is not None:
            # We are trying to attach section to the course
            try:
                course = Course.objects.get({'_id': uuid.UUID(course_uuid)})
            except ValueError:
                return HttpResponse('non-UUID id was passed', status=400)
            except Course.DoesNotExist:
                return HttpResponse('Error: course with passed UUID does not exist', status=404)

        # Map types to pymodm classes
        for c in section['contents']:
            if c['type'] == 'text':
                c['_cls'] = 'material_api.models.content.ContentText'
            elif c['type'] == 'code':
                c['_cls'] = 'material_api.models.content.ContentCode'
            elif c['type'] == 'image':
                c['_cls'] = 'material_api.models.content.ContentImage'
            elif c['type'] == 'file':

DigitalLibrary/materials/templates/materials/material_request.html
{% extends "base.html" %}

{% block content %}
    <h1>Request a material</h1>
    <hr>
    <form method="post" action="{% url 'materials:material_request' %}">
        {% csrf_token %}

        {{ form.as_table }}
        <input style="margin-left: auto; margin-right: auto;" type="submit" value="Send">
    </form>
{% endblock %}

DigitalLibrary/materials/templates/materials/material_request_success.html
{% extends "base.html" %}

{% block content %}
    <h1>Request a material</h1>
    <p>Your request was successfully submitted.</p>
    <p>Wait for the moderator to contact you via Telegram.</p>
{% endblock %}

DigitalLibrary/materials/templates/materials/material_requests_list.html
{% extends "base.html" %}

{% block content %}
    <style>
        h1, h2, h3, h4, h5, h6 {
            text-align: center;
        }

        td, th {
            padding: 6px 16px;
            text-align: left;
        }

        th {
            white-space: nowrap;
        }

        .request {
            background-color: var(--background-alt);
            border-radius: 8px;
            padding: 8px;
            margin: 8px 0;
        }
    </style>

    <h1>Material requests</h1>
    <hr>

    {% if list %}
        {% for e in list %}
            <div class="request">
                <table>
                    <tr style="border-bottom: 1px solid var(--background-alt2);">
                        <th>Requester</th>
                        <td><a href="/users/user_info/{{ e.user_id }}">{{ e.user.username }}</a></td>
                    </tr>
                    <tr style="border-bottom: 1px solid var(--background-alt2);">
                        <th>Title</th>
                        <td>{{ e.title }}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid var(--background-alt2);">
                        <th>Body</th>
                        <td style="text-align: justify">{{ e.body|linebreaks }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <a class="fake-link" href="/materials/remove_material_request/{{ e.id }}">
                                <button class="dangerous-button">Remove</button>
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
        {% endfor %}

    {% else %}
        <p style="margin-left: auto; margin-right: auto;">No requests were made. Come back later!</p>
    {% endif %}


{% endblock %}

DigitalLibrary/materials/templates/materials/searchbar_results.html
{% load dict_tags %}

<style>
    .searchbar-results-content {
        display: flex;
        flex-direction: column;
        margin: 8px 0 8px 0;
    }

    .searchbar-results-heading {
        margin: 8px 0 8px 0;
    }

    .searchbar-results-content > p {
        margin: 8px 0;
    }

    .searchbar-results-content > hr {
        width: 100%;
    }
</style>

<div class="searchbar-results-content">
    {% if courses %}
        <h2 class="searchbar-results-heading">Courses</h2>
        {% for course in courses %}
            <p><a href="/materials/course_page/{{ course.0 }}">{{ course.1 }}</a></p>
        {% endfor %}
        {% if sections %}
            <hr>
        {% endif %}
    {% endif %}

    {% if sections %}
        <h2 class="searchbar-results-heading">Sections</h2>
        {% for section in sections %}
            <p><a href="/materials/section_page/{{ section.0 }}">{{ section.1 }}</a></p>
        {% endfor %}
        {% if files %}
            <hr>
        {% endif %}
    {% endif %}

    {% if files %}
        <h2 class="searchbar-results-heading">Files</h2>
        {% for file in files %}
            <p>
                <img src="{{ icons|get_item:file.0 }}" style="width: 24px; height: 24px; vertical-align: middle; margin-top: -6px;">
                <a href="/materials/file_info/{{ file.0 }}">{{ file.1 }}</a></p>
        {% endfor %}
    {% endif %}

    {% if not courses and not sections and not files %}
        <p>Nothing found.</p>
    {% endif %}
</div>

DigitalLibrary/materials/templates/materials/section.html
{% load permission_tags %}
{% load dict_tags %}


<div class="section">
    <h2>
        {{ section.name }}
    </h2>
    {% if user|has_perm:"auth.moderate" and edit == "true" %}
        <p>
            <a href="/materials/edit_section/{{ section.uuid }}">Edit</a>
            |
            <a style="color: var(--text-dangerous)"
               href="/materials/delete_section_from_course/{{ course.uuid }}/{{ section.uuid }}">Delete</a>
        </p>
    {% endif %}

    {% if not section.contents %}
        {# Handle the case of empty section #}
        <p>This section is empty.</p>
    {% else %}
        {# Show all the attached content if section is non-empty #}
        {% for content in section.contents %}
            {% ifequal content.type 'text' %}
                <p>{{ content.text|linebreaksbr|urlize }}</p>
            {% endifequal %}
            {% ifequal content.type 'code' %}
                <pre><code class="monospace-text">{{ content.code }}</code></pre>
            {% endifequal %}
            {# TODO: add async images #}
            {% ifequal content.type 'image' %}
                <img src="/resources/images/{{ content.hash }}"
                     width="{{ content.width }}" height="{{ content.height }}" alt="{{ content.name }}"/>
            {% endifequal %}
            {% ifequal content.type 'file' %}
                {% if content.file == None %}
                    <div class="material_entry">
                        <a>ERROR! REFERENCED FILE DOES NOT EXIST!</a>
                    </div>
                {% else %}
                    {#                            <div class="material_entry">#}
                    {#                                <img class="material_icon" src="{{ icons|get_item:content.file.hash }}"/>#}
                    {#                                <a href="/materials/file_info/{{ content.file.hash }}">{{ content.file.name }}</a>#}
                    {#                            </div>#}

                    <a class="fake-link" href="/materials/download/{{ content.file.hash }}">
                        <div class="file-picker-entry">
                            <img src="{{ icons|get_item:content.file.hash }}" alt="icon"
                                 style="width: 48px; height: 48px; margin: 8px 8px 8px 0;"/>
                            <div>
                                <h4 class="sans-serif file-picker-filename">{{ content.file.name }}</h4>
                                <span class="sans-serif file-picker-filesize">Size: {{ content.file.size|filesizeformat }}</span>
                                <span class="sans-serif file-picker-create-info">Uploaded {{ content.file.create_date }}</span>
                            </div>
                        </div>
                    </a>
                {% endif %}
            {% endifequal %}
        {% endfor %}
    {% endif %}
</div>

DigitalLibrary/materials/templates/materials/section_page.html
{% extends "base.html" %}

{% block content %}
    {% include 'materials/section.html' %}
{% endblock %}