DigitalLibrary/DigitalLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('our_auth/', include('our_auth.urls')),
    path('materials/', include('materials.urls')),
    path('users/', include('users.urls')),
    path('copyright/', include('copyright.urls')),
]

DigitalLibrary/materials/urls.py
from django.urls import path
from . import views

app_name = 'materials'
urlpatterns = [
    path('course_page/<str:course_uuid>', views.course_page, name='course_page'),
    path('course_list/', views.course_list, name='course_list'),
    path('create_course/', views.create_course, name='create_course'),
    path('edit_section/<str:section_uuid>', views.edit_section, name='edit_section'),
    path('delete_section_from_course/<str:course_uuid>/<str:section_uuid>', views.delete_section_from_course, name='delete_section_from_course'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('file_info/<str:file_hash>', views.file_info, name='file_info'),
    path('file_list', views.file_list, name='file_list'),
    path('save_section/<str:section_uuid>', views.save_section, name='save_section'),
    path('save_course_name_subtitle/<str:course_uuid>', views.save_course_name_subtitle, name='save_course_name_subtitle'),
    path('validate_course_structure/<str:course_uuid>', views.validate_course_structure, name='validate_course_structure'),
    path('api_fetch_file_list', views.api_fetch_file_list, name='api_fetch_file_list'),
    path('download/<str:file_hash>', views.download, name='download'),
    path('material_request', views.material_request, name='material_request'),
    path('material_request_success', views.material_request_success, name='material_request_success'),
    path('material_requests_list', views.material_requests_list, name='material_requests_list'),
    path('remove_material_request/<int:req_id>', views.remove_material_request, name='remove_material_request'),
    path('delete_file/<str:file_hash>', views.delete_file, name='delete_file'),
    path('searchbar_search/<str:query>', views.searchbar_search, name='searchbar_search'),
    path('section_page/<str:section_uuid>', views.section_page, name='section_page'),
]

DigitalLibrary/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('user_info/<int:user_id>', views.user_info, name='user_info'),
]

DigitalLibrary/materials/models.py
from django.contrib.auth.models import User
from django.db import models


class MaterialRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=127)
    body = models.TextField()
    telegram_alias = models.CharField(max_length=127)

DigitalLibrary/materials/forms.py
from django import forms

from material_api.models.course import Course
from materials.models import MaterialRequest
from our_auth.models import SignupSubmission


class CreateCourseForm(forms.Form):
    name = forms.CharField(max_length=255, label='Course name')
    subtitle = forms.CharField(max_length=255, label='Course subtitle')


class UploadFileForm(forms.Form):
    name = forms.CharField(max_length=255)
    file = forms.FileField()


class MaterialRequestForm(forms.ModelForm):
    title = forms.CharField(max_length=127, label='Title')
    body = forms.Textarea()
    telegram_alias = forms.CharField(max_length=127, label='Telegram Alias')

    class Meta:
        model = MaterialRequest
        fields = ('title', 'body', 'telegram_alias')

DigitalLibrary/materials/views.py
import json
import uuid
from json import JSONDecodeError

from django.contrib import messages
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from pymodm.errors import DoesNotExist

from DigitalLibrary import utils, icons
from material_api import search
from material_api.models.content import ContentFile
from material_api.models.course import Course
from material_api.models.file import File
from material_api.models.section import Section
from materials.forms import CreateCourseForm, UploadFileForm, MaterialRequestForm
from materials.models import MaterialRequest
from users import user_api


def course_list(request):
    courses = list(Course.objects.all())

    # TODO: implement group checking
    # TODO: implement recent courses

    return render(request, 'course_list.html', {'courses': courses})


def validate_course_structure(request, course_uuid):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    try:
        course = Course.objects.get({'_id': uuid.UUID(course_uuid)})

        changed = False
        for section in course.sections:
            print(section)
            if section is None:
                course.sections.remove(section)
                changed = True

        if changed:
            course.save()

        return redirect('/materials/course_page/%s' % course_uuid)
    except Course.DoesNotExist:
        return render(request, '404.html', {'message': 'Course with given UUID was not found'})


def course_page(request, course_uuid):
    try:
        course = Course.objects.get({'_id': uuid.UUID(course_uuid)})

        icons_dict = {}
        for section in course.sections:
            for content in section.contents:
                if type(content) == ContentFile:
                    file = content.file
                    if file is not None:
                        icons_dict[file.hash] = icons.getIconURL(file.extension)

        return render(request, 'course_page.html',
                      {'course': course, 'icons': icons_dict, 'edit': request.GET.get('edit', 'false')})
    except ValueError:
        return render(request, '404.html', {'message': 'Your link is corrupted, please, recheck it'})
    except Course.DoesNotExist:
        return render(request, '404.html', {'message': 'Course with given UUID was not found'})


def create_course(request):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    if request.method == 'POST':
        form = CreateCourseForm(request.POST)
        if form.is_valid():
            data = request.POST.copy()
            color1, color2 = Course.gen_color()
            name = data.get('name')
            course = Course(uuid.uuid4(), name, data.get('subtitle'), color1, color2, [
                Section(uuid.uuid4(), 'Information about ' + name, [], []),
                Section(uuid.uuid4(), 'Books: ' + name, [], []),
                Section(uuid.uuid4(), 'Videos: ' + name, [], []),
                Section(uuid.uuid4(), 'Links: ' + name, [], [])
            ])
            course.save(cascade=True)
            return redirect('/materials/course_page/%s' % course.uuid)
        else:
            messages.error(request, form.errors)
    else:
        return render(request, 'create_course.html', {'form': CreateCourseForm()})


def edit_section(request, section_uuid):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    try:
        if section_uuid == 'new':
            # We are trying to create new section

            # Check if we know which course attach this section to
            course = request.GET.get('course_uuid', None)
            if course is None:
                return render(request, '400.html',
                              {'message': {'Trying to create a new section, but no course is specified for it.'}})

            new = True
            section = Section(uuid.uuid4(), 'New section', [], [])
        else:
            # We are updating existing section
            new = False
            section = Section.objects.get({'_id': uuid.UUID(section_uuid)})

        son = section.to_son()

        print(son)

        # Custom handling of content list, since we want to include their content into response, not just _id's.
        for i, c in enumerate(son['contents']):
            if c['type'] == 'file':
                # Check if non-existing file is referenced
                if section.contents[i].file is None:
                    c['file_info'] = File(hash='', name='ERROR! FILE DOES NOT EXIST').to_son()
                else:
                    c['file_info'] = section.contents[i].file.to_son()

        section_document = json.dumps(son.to_dict(), cls=DjangoJSONEncoder) \
            .replace('\\', '\\\\').replace('<', '\\<').replace('>', '\\>')

        return render(request, 'section_editor.html',
                      {'new': new, 'section': section, 'section_document': section_document})
    except ValueError:
        return render(request, '400.html', {'message': 'Your link is corrupted, please, recheck it'})
    except Course.DoesNotExist:
        return render(request, '404.html', {'message': 'Course with given UUID was not found'})
    except Section.DoesNotExist:
        return render(request, '404.html', {'message': 'Section with given UUID was not found'})


def delete_section_from_course(request, course_uuid, section_uuid):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    try:
        course = Course.objects.get({'_id': uuid.UUID(course_uuid)})
        section = Section.objects.get({'_id': uuid.UUID(section_uuid)})
        approved = request.GET.get('approved', 'false')

        # TODO: complete this!
        if approved == 'true':
            course.sections.remove(section)
            course.save()
            return redirect('/materials/course_page/' + course_uuid)
        else:
            return render(request, 'delete_section_from_course.html', {'course': course, 'section': section})
    except ValueError:
        return render(request, '400.html', {'message': 'Your link is corrupted, please, recheck it'})
    except Course.DoesNotExist:
        return render(request, '404.html', {'message': 'Course with given UUID was not found'})
    except Section.DoesNotExist:
        return render(request, '404.html', {'message': 'Section with given UUID was not found'})


def upload_file(request):
    """
    Serves the page for file upload and accepts files sent with file upload form.

    :param request: Django request object
    :return: page with form or redirection to page with info about newly uploaded file
    """
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            # Only allow direct upload for moderators, for all other users, set "pending" flag.
            pending = not request.user.has_perm('auth:moderate')
            f = File.create_from_data(request.user.id, pending, form.cleaned_data.get('name'), request.FILES['file'])
            return redirect('/materials/file_info/%s' % f.hash)
    else:
        form = UploadFileForm()
    return render(request, 'upload_file.html', {'form': form})


def file_info(request, file_hash):
    try:
        file = File.objects.get({'_id': file_hash})
    except File.DoesNotExist:
        return render(request, '404.html', {'message': 'File with given hash was not found'})

    uploader_name = ''
    if request.user.has_perm('auth.moderate'):
        uploader_name = user_api.get_username(file.uploader)

    icon = icons.getIconURL(file.extension)

    return render(request, 'file_info.html', {'file': file, 'uploader_name': uploader_name, 'icon': icon})


def file_list(request):
    # Get page number, if any was provided by user in the "page" argument
    page_number = request.GET.get('page', 0)
    if type(page_number) == str:
        try:
            page_number = int(page_number)
        except ValueError:
            return render(request, '400.html', {'message': 'Page number should be integer number'})

    page_size = 5

    files = File.objects.skip(page_number * page_size).limit(page_size).all()

    return render(request, 'file_list.html', {'page': page_number, 'files': files})


def save_section(request, section_uuid):
    if not request.user.has_perm('auth.moderate'):
        return render(request, '404.html', {'message': 'Go. Away.'})

    # only accept POST requests here
    if request.method != 'POST':
        return render(request, '400.html', {'message': 'Expected POST request'})

    try:
        section = json.loads(request.body)

        # Check if we are creating new section & attaching it to the course
        course_uuid = request.GET.get('course_uuid', None)
        course = None
        if course_uuid is not None:
            # We are trying to attach section to the course
            try:
                course = Course.objects.get({'_id': uuid.UUID(course_uuid)})
            except ValueError:
                return HttpResponse('non-UUID id was passed', status=400)
            except Course.DoesNotExist:
                return HttpResponse('Error: course with passed UUID does not exist', status=404)

        # Map types to pymodm classes
        for c in section['contents']:
            if c['type'] == 'text':
                c['_cls'] = 'material_api.models.content.ContentText'
            elif c['type'] == 'code':
                c['_cls'] = 'material_api.models.content.ContentCode'
            elif c['type'] == 'image':
                c['_cls'] = 'material_api.models.content.ContentImage'
            elif c['type'] == 'file':

DigitalLibrary/materials/templates/course_list.html
{% extends "base.html" %}
{% load permission_tags %}

{% block content %}
    <style>
        .courses {
            display: flex;
            flex-direction: row;
            flex-flow: wrap;
        }

        .course {
            width: calc(50% - 16px);
            height: 200px;
            margin: 8px;
        }

        .course-content {
            width: calc(100% - 40px);
            height: calc(100% - 40px);
        {#background: linear-gradient(#2a9e2c, #227924);#} border-radius: 4px;
            box-shadow: 0 0 8px rgba(0, 0, 0, 0.4);
            padding: 20px;
            color: white;
            cursor: pointer;
        }

        .course-name {
            margin: 0;
            color: white;
        }

        .course-subtitle {

        }

        @media (max-width: 700px) {
            .course-name {
                font-size: 1.8em;
            }

            .course {
                width: calc(50% - 8px);
                margin: 4px;
            }
        }

        @media (max-width: 650px) {
            .course {
                width: 100%;
            }
        }

        .recent-courses {
            display: flex;
            flex-direction: column;
        }

        .recent-course {
        {#height: 100px;#}
        }

        .recent-course-content {
            background: linear-gradient(#2a9e2c, #227924);
            border-radius: 4px;
            box-shadow: 0 0 8px rgba(0, 0, 0, 0.4);
            padding: 16px 24px;
            color: white;
            margin: 4px;
        }

        .recent-course-subtitle {
            margin: 8px 0;
        }

    </style>

    <br>
    <h1>Recent courses</h1>
    <br>

    <br><br>
    <h1>All courses</h1>
    <br>

    <div class="courses">

        {% for course in courses %}
            <div class="course">
                <a href="/materials/course_page/{{ course.uuid }}" class="fake-link">
                    <div class="course-content sans-serif"
                         style="background: linear-gradient({{ course.course_color_1 }}, {{ course.course_color_2 }});">
                        <h1 class="course-name">{{ course.name }}</h1>
                        <p class="course-subtitle">{{ course.subtitle }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}

    </div>

    <br>

    {% if user|has_perm:"auth.moderate" %}
        <div style="margin: auto; display: flex; flex-direction: column; align-items: center;">
            {#        <h3>Missing something?</h3>#}
            {##}
            {#        <button class="accent-button">Upload own materials</button>#}
            <button class="accent-button" onclick="location.href='/materials/create_course'">Create course
            </button>
        </div>
    {% endif %}

    <hr style="width: 100%;">
    <div style="margin: auto; display: flex; flex-direction: column; align-items: center;">
        <p style="color: var(--text-muted); margin-bottom: 4px; margin-top: 0px; text-align: center">See your own
            material here, but
            you
            did not allow its publication? <a href="/copyright/claim">Make a copyright complaint</a></p>
    </div>
{% endblock %}

DigitalLibrary/materials/templates/course_page.html
{% extends "base.html" %}
{% load permission_tags %}
{% load dict_tags %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="/static/materials/file_picker.css">

    <style>
        .section {
            padding-left: 8px;
            border-left: 3px solid var(--border);
        }

        .material_entry {
            display: flex;
            flex-direction: row;
            align-items: center;
            background-color: var(--background-alt);
            width: max-content;
            padding: 6px 16px 6px 6px;
            border-radius: 4px;
            margin: 8px 0;
        }

        .material_icon {
            width: 32px;
            height: 32px;
            margin-right: 8px;
        }
    </style>


    {% if user|has_perm:"auth.moderate" and edit == "true" %}

        <label for="name">Course name</label>
        <span id="name" contenteditable="true" class="input">{{ course.name }}</span>
        <br>

        <label for="subtitle">Subtitle</label>
        <span id="subtitle" contenteditable="true" class="input">{{ course.subtitle }}</span>
        <br>

        <div>
            <button onclick="save_name_subtitle()">Save name & subtitle</button>
            <span style="margin: 0 8px" id="save_status"></span>
        </div>
    {% else %}
        <h1>{{ course.name }}</h1>
        <p>{{ course.subtitle }}</p>
    {% endif %}
    <hr>

    {% for section in course.sections %}
        {% include 'materials/section.html' %}
    {% endfor %}

    <br>
    <div style="margin: auto; display: flex; flex-direction: column; align-items: center;">

        {% if edit != 'true' %}
            <h3>Missing something?</h3>
            <div>
                <a class="fake-link" href="/materials/upload_file">
                    <button class="accent-button">Upload own materials</button>
                </a>
                <a class="fake-link" href="/materials/material_request">
                    <button class="accent-button">Request a material</button>
                </a>
            </div>
        {% endif %}

        {% if user|has_perm:"auth.moderate" %}
            <hr style="width: 100%;">
            <h3 style="margin: 8px auto">Adminish stuff</h3>
            <div>

                {% if edit != 'true' %}

                    <a href="/materials/edit_section/new?course_uuid={{ course.uuid }}" class="fake-link">
                        <button class="accent-button">Create section</button>
                    </a>
                    <a href="/materials/validate_course_structure/{{ course.uuid }}" class="fake-link">
                        <button class="accent-button">Validate structure</button>
                    </a>
                    <a href="/materials/course_page/{{ course.uuid }}?edit=true" class="fake-link">
                        <button class="accent-button">Edit sections</button>
                    </a>

                {% else %}

                    <a href="/materials/course_page/{{ course.uuid }}" class="fake-link">
                        <button class="dangerous-button">Stop editing</button>
                    </a>

                {% endif %}

            </div>
        {% endif %}
    </div>

    <hr style="width: 100%;">
    <div style="margin: auto; display: flex; flex-direction: column; align-items: center;">
        <p style="color: var(--text-muted); margin-bottom: 4px; margin-top: 0; text-align: center">See your own
            material here, but
            you
            did not allow its publication? <a href="/copyright/claim">Make a copyright complaint</a></p>
    </div>


    {% if user|has_perm:"auth.moderate" and edit == "true" %}
        <script>
            course_uuid = "{{ course.uuid }}"
        </script>
        <script src="/static/materials/course_editor.js"></script>
    {% endif %}

{% endblock %}

DigitalLibrary/materials/templates/create_course.html
{% extends "base.html" %}
{% load permission_tags %}

{% block content %}

    <h1>Create new course</h1>
    <form method="post" action="{% url 'materials:create_course' %}">
        {% csrf_token %}

        <table style="margin-left: auto; margin-right: auto;">
            {{ form.as_table }}
        </table>

        <input style="margin-left: auto; margin-right: auto;" type="submit" value="Create">
    </form>

{% endblock %}

DigitalLibrary/materials/templates/delete_section.html
{% extends "base.html" %}

{% block content %}
    <h1>Deleting section</h1>
    <p>Are you sure you want to delete section <b>{{ section.name }}</b> from course <b>{{ course.name }}</b>?</p>
    <a href="/"></a><button
{% endblock %}

DigitalLibrary/materials/templates/delete_section_from_course.html
{% extends "base.html" %}

{% block content %}
    <h1>Deleting section</h1>
    <p>Are you sure you want to delete section <b>{{ section.name }}</b> from course <b>{{ course.name }}</b>?</p>
    <div>
        <a href="/materials/delete_section_from_course/{{ course.uuid }}/{{ section.uuid }}?approved=true">
            <button class="dangerous-button">Delete</button>
        </a>
        <a href="/course_page/{{ course.uuid }}">
            <button>Cancel</button>
        </a>
    </div>
{% endblock %}

DigitalLibrary/materials/templates/file_info.html
{% extends "base.html" %}
{% load permission_tags %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="/static/materials/file_picker.css">

    <h1>File info</h1>

    <div class="file-picker-entry">
        <img src="{{ icon }}" alt="icon" style="width: 48px; height: 48px; margin: 8px 8px 8px 0;"/>
        <div>
            <h4 class="sans-serif file-picker-filename">{{ file.name }}</h4>
            <span class="sans-serif file-picker-filesize">Size: {{ file.size|filesizeformat }}</span>
            <span class="sans-serif file-picker-create-info">
                            Uploaded {{ file.create_date }} by
                            <a href="/users/user_info/{{ file.uploader }}" onclick="stopPropagation(this)"
                               target="_blank">{{ uploader_name }}</a>
                        </span>
        </div>
    </div>

    <table>
        <tr>
            <th>Hash</th>
            <td>{{ file.hash }}</td>
        </tr>
        <tr>
            <th>File name</th>
            <td>{{ file.name }}</td>
        </tr>
        <tr>
            <th>Creation date</th>
            <td>{{ file.create_date }}</td>
        </tr>
        <tr>
            <th>Size</th>
            <td>{{ file.size|filesizeformat }}</td>
        </tr>
        <tr>
            <th>Allowed groups</th>
            <td>{{ file.allowed_groups }}</td>
        </tr>

        <tr>
            <th>Uploader</th>
            <td><a href="/users/user_info/{{ file.uploader }}">{{ uploader_name }}</a></td>
        </tr>

    </table>
{% endblock %}

DigitalLibrary/materials/templates/file_list.html
{% extends "base.html" %}

{% block content %}
    <style>
        h1, h2, h3, h4, h5, h6 {
            text-align: center;
        }

        div.content {
            max-width: none;
        }

        td, th {
            padding: 6px 16px;
        }

        th {
            text-align: center;
        }

        table {
            border: 1px solid var(--text-muted);
            margin-left: auto;
            margin-right: auto;
        }
    </style>

    <h1>All files</h1>
    <h2>Page {{ page }}</h2>

    <table border="1">
        <tr>
            <th>Hash</th>
            <th>Name</th>
            <th>Created at</th>
            <th>Uploader</th>
            <th>Size</th>
            <th>Allowed groups</th>
            <th>Pending</th>
            <th>Download</th>
            <th>Delete</th>
        </tr>

        {% for file in files %}
            <tr>
                <td class="monospace-text">{{ file.hash }}</td>
                <td>{{ file.name }}</td>
                <td>{{ file.create_date }}</td>
                <td>{{ uploader }}</td>
                <td>{{ file.size|filesizeformat }}</td>
                <td>{{ file.allowed_groups }}</td>
                <td>{{ file.pending }}</td>
                <td><a href="/materials/download/{{ file.hash }}">Download</a></td>
                <td><a href="/materials/delete_file/{{ file.hash }}" style="color: var(--text-dangerous)">Delete</a></td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

DigitalLibrary/materials/templates/section_editor.html
{% extends "base.html" %}

{% block content %}
    <style>
        .add_materials_buttons {
            display: flex;
            flex-direction: row;
            justify-content: center;
            flex-wrap: wrap;
        }

        .material_list {
            display: flex;
            flex-direction: column;
            justify-content: stretch;
        }

        .material_entry {
            background-color: var(--background-alt);
            padding: 8px;
            margin: 1px 0;
            border-radius: 4px;
            display: flex;
            flex-direction: row;
            align-items: center;
            justify-content: space-between;
        }

        .move-up-button, .move-down-button {
            color: var(--text-muted);
            padding: 0 4px;
            width: 24px;
            border-radius: 4px;
        }

        .move-up-button:hover, .move-down-button:hover {
            background-color: var(--background);
        }

        .move-up-button:active, .move-down-button:active {
            background-color: var(--background-alt2);
        }

        .delete-button {
            color: var(--text-dangerous);
            margin: 2px 8px;
        }

        .material-entry-buttons {
            display: flex;
            flex-direction: column;
            align-items: center;
            min-width: fit-content;
        }
    </style>

    {% if new %}
        <h1>Create section</h1>
    {% else %}
        <h1>Edit section</h1>
        <h2>{{ section.name }}</h2>
    {% endif %}
{#    <h2>Debug info</h2>#}
{#    <p>Section UUID: {{ section.uuid }}</p>#}

    <div id="{{ section.uuid }}" class="material">
        <label for="name">Name</label>
        <span id="name" contenteditable="true" class="input"></span>
        <br>
        <br>
        <label for="name">Tags</label>
        <span id="tags" contenteditable="true" class="input"></span>
        <br>
        <span class="small-text">Put comma-separated tags here.<br>All spaces are omitted, so put as many as you'd like.</span>
        <hr>

        <h2>Materials</h2>

        <div class="material_list" id="material_list">
        </div>

        <div class="add_materials_buttons">
            <button onclick="addText(genLocalContentID(), '')">Add text</button>
            <button onclick="addCode(genLocalContentID(), '')">Add code</button>
{#            <button onclick="addImage(genLocalContentID(), null)">Add image</button>#}
            <button onclick="addFile(genLocalContentID(), null)">Add file</button>
        </div>

        <hr>
        <div>
            <button onclick="save()">{{ new|yesno:"Create,Save" }}</button>
            <p style="display: inline;" id="save_status"></p>
        </div>
    </div>

    <link rel="stylesheet" type="text/css" href="/static/materials/file_picker.css">

    <script src="/static/materials/section_editor.js"></script>
    <script src="/static/materials/file_picker.js"></script>
    <script>
        course_uuid = `{{ course.uuid }}`
        section_uuid = `{{ section.uuid }}`
        {#section_document = htmlDecode(`{{ section_document }}`).replace(/\n/g, '\\n')//.replace(/"/g, '\"')#}
        {% autoescape off %}
            console.log(`{{ section_document }}`)
            section_document = htmlDecode(`{{ section_document }}`)
        {% endautoescape %}
        console.log(section_document)
        load(section_document)
    </script>
{% endblock %}

DigitalLibrary/materials/templates/upload_file.html
{% extends "base.html" %} {% block content %}
<h1>Upload new file</h1>

<form method="post" enctype="multipart/form-data" action="{% url 'materials:upload_file' %}">
    {% csrf_token %}

    <table style="margin-left: auto; margin-right: auto;">
        {{ form.as_table }}
    </table>

    <input style="margin-left: auto; margin-right: auto;" type="submit" value="Create">
</form>
{% endblock %}